name: Successfully-build-application
on:
  pull_request:
    branches: [ develop, main, test ]

  push:
    branches: [ develop, main, test ]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      - name: Install app dependencies
        run: pnpm install --frozen-lockfile
      - name: Build app
        run: pnpm run build